exclude: |
    (?x)^(
        exercises/practice/.*/.docs/introduction.md|
        exercises/practice/.*/.docs/instructions.md|
        .*/vendor/.*|
        .github/CODEOWNERS
    )$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.3
    hooks:
    -   id: clang-format
        exclude_types: [json]
-   repo: local
    hooks:
    -   id: update-from-templates
        name: Check that all exercises use up-to-date copies from templates dir
        language: system
        entry: bin/update-from-templates
        pass_filenames: false
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
        - id: ruff
          args: [--fix]
        - id: ruff-format
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
